export const KNOWN_MUTATION_SUFFIXES = {
  CREATE_ENDPOINT_MUTATION: 'CREATE_ENDPOINT',
  NOTIFICATION_UPDATE_MUTATION: 'NOTIFICATION_UPDATE',
  SECURITY_UPDATE_MUTATION: 'SECURITY_UPDATE',
  SEND_RESET_EMAIL_MUTATION: 'SEND_RESET_EMAIL',
  VALIDATE_USER_MUTATION: 'VALIDATE_USER_MUTATION',
}

export const KNOWN_QUERY_SUFFIXES = {
  DAILY_BREAKDOWN_METRICS: 'DAILY_BREAKDOWN_METRICS',
  HOURLY_LATENCY_METRICS: 'HOURLY_LATENCY_METRICS',
  LATEST_FILTERED_DETAILS: 'LATEST_FILTERED_DETAILS',
  LATEST_RELAYS: 'LATEST_RELAYS',
  METRICS: 'METRICS',
  ONCHAIN_DATA: 'ONCHAIN_DATA',
  ORIGIN_CLASSIFICATION: 'ORIGIN_CLASSIFICATION',
  PREVIOUS_SUCCESSFUL_METRICS: 'PREVIOUS_SUCCESSFUL_METRICS',
  PREVIOUS_TOTAL_METRICS: 'PREVIOUS_TOTAL_METRICS',
  SESSION_METRICS: 'SESSION_METRICS',
  STAKEABLE_CHAINS: 'STAKEABLE_CHAINS',
  USER_APPS: 'USER_APPS',
  USER_CONTEXT: 'USER_CONTEXT',
  WEEKLY_SUCCESSFUL_METRICS: 'WEEKLY_SUCCESSFUL_METRICS',
  WEEKLY_TOTAL_METRICS: 'WEEKLY_TOTAL_METRICS',
}
